name: r312
description: "Remote control for the u312"
publish_to: 'none' # never publish
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  bordered_text: ^2.0.0
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_background: ^1.3.0+1
  flutter_blue_classic: ^0.0.4
  flutter_libserialport: ^0.5.0
  google_fonts: ^6.2.1
  material_symbols_icons: ^4.2815.0
  mqtt_client: ^10.8.0
  provider: ^6.1.5
  qr_flutter: ^4.1.0
  serial: ^0.0.7+1
  web: ^1.1.1

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  # dart run flutter_launcher_icons
  image_path: "assets/icon.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/icon.png"
  android: true
  web:
    generate: true
  macos:
    generate: true